import React from 'react'
import "@/styles/other/other.css"

const TermsConditionsPage = () => {
    return (
        <>
            <main>
                <section>
                    <div className="terms-condition">
                        <div className="content">
                            <h1 data-animate="zoom-in">Terms and Conditions</h1>

                            <h2>Terms & Conditions for Suppliers</h2>
                            <h3>Terms & Conditions for S & M Group, Inc. dba Flextron Circuit Assembly(FCA)'s Suppliers, applicable to the FCA's Purchase Orders.</h3>

                            <h4>All S & M Group, Inc. dba Flextron Circuit Assembly(FCA)’s Purchase Orders are subject to our terms and conditions as below including special and additional requirement parts.</h4>

                            <h5>1. REVOCATION AND EFFECT OF ORDER</h5>
                            <p>Purchase Order (“Order”) may be revoked at any time prior to FCA’s receipt of written acceptance by Seller. This Order expressly limits acceptance to the terms of this Order and FCA hereby objects to any different or additional terms contained in any response to this Order. To the extent that this Order might be treated as an acceptance of Seller’s prior offer, such acceptance is expressly made on condition of assent by Seller to the terms hereof, and the shipment of the products covered by this Order (“Goods”) or work performed by Seller (“Services”) shall constitute such assent. In addition to the other terms in this Order, this Order expressly includes all implied warranties and all of FCA’s remedies set forth in the Uniform Commercial Code and similar laws in other countries. The terms of this Order are the sole and exclusive terms on which FCA agrees to be bound.</p>

                            <h5>2. DELIVERY</h5>
                            <p>Time is of the essence in Order. Delivery of the Goods and performance of any Services shall be made pursuant to the schedule, via the carrier, and to the place specified on the face hereof unless changed by written instructions from FCA prior to shipment or performance. Seller shall promptly inform FCA of any anticipated delay in shipment or performance. FCA reserves the right to return, shipping charges collect, all Goods received more than three (3) business days in advance of the specified delivery date or after the specified delivery date. If Order calls for delivery in installments and Seller fails to deliver an installment on the designated delivery date, FCA may decline to accept subsequent installments and terminate the balance of Order.</p>

                            <h5>3. SHIPPING INSTRUCTIONS</h5>
                            <p>Unless otherwise specified on the face hereof, all Goods shall be packaged by Seller in suitable containers to permit safe transportation and handling. Each delivered container must be labeled and marked to identify contents without opening, and all boxes and packages must contain packing sheets listing contents. FCA’s purchase order number, as well as FCA’s part number(s), must appear on all shipping containers, packing sheets, delivery tickets, and bills of lading. All Goods shall be shipped on carriers certified compliant with C-TPAT (Customs-Trade Partnership Against Terrorism).</p>

                            <h5>4. TITLE AND RISK OF LOSS</h5>
                            <p>Unless otherwise specified on Order, Goods shall be delivered DDP FCA’s location designated on the face hereof (Incoterms 2010), at which time title and risk of loss on the Goods shall pass to FCA. If any of the ordered Goods are destroyed or materially damaged prior to the time risk of loss passes to FCA, FCA may cancel Order as to the destroyed or materially damaged Goods or require the prompt delivery of substitute Goods of equal quantity and quality.</p>

                            <h5>5. PRICE AND PAYMENT</h5>
                            <p>The price to be paid by FCA for the Goods shall be that stated on the face hereof. Payment terms shall be net sixty (60) days from FCA’s receipt of Goods or, if applicable, acceptance of Services unless otherwise specified on the face hereof. Seller invoices must list only one FCA item number and one FCA purchase order number, unless the invoices are for “maintenance, repair and operations” (“MRO”) items. Unless otherwise specified on the face hereof, the price of the Goods includes all shipping charges, taxes, VAT, duties and packaging. Personal property taxes assessable upon the Goods prior to the receipt by FCA shall be borne by Seller. As full consideration for the performance of the Services, delivery of the Goods and the assignment of rights to FCA as provided herein, FCA shall pay Seller (i) the amount agreed upon and specified in the applicable Order, or (ii) Seller’s quoted price on date of shipment (for Goods), or the date Services were started (for Services), whichever is lower. Applicable taxes and other charges such as shipping costs, duties, customs, tariffs, imposts and government imposed surcharges shall be stated separately on Seller’s invoice. Payment is made when FCA’s check is mailed. Payment shall not constitute acceptance. All personal property taxes assessable upon the Goods prior to receipt by FCA of Goods conforming to the Order shall be borne by Seller. Seller shall invoice FCA for all Goods delivered and all Services actually performed. Each invoice submitted by Seller must be provided to FCA within ninety (90) days of completion of the Services or delivery of Goods and must reference the applicable Order, and FCA reserves the right to return all incorrect invoices. FCA will receive a 2% discount of the invoiced amount for all invoices that are submitted more than ninety (90) days after completion of the Services or delivery of the Goods. Unless otherwise specified on the face of a Order, FCA shall pay the invoiced amount within sixty (60) days after receipt of a correct invoice. Seller will receive no royalty or other remuneration on the production or distribution of any products developed by FCA or Seller in connection with or based on the Goods or Services provided.</p>

                            <h5>6. INSPECTION</h5>
                            <p>FCA shall have a reasonable time after receipt of Goods or Service deliverables and before payment to inspect them for conformity hereto, and Goods received prior to inspection shall not be deemed accepted until FCA has run an adequate test to determine whether the Goods conform to the specifications hereof. Use of a portion of the Goods for the purpose of testing shall not constitute an acceptance of the Goods. If Goods tendered do not wholly conform with the provisions hereof, FCA shall have the right to reject such Goods. Nonconforming Goods will be returned to Seller freight collect and risk of loss will pass to Seller upon FCA’s delivery to the common carrier.</p>

                            <h5>7. WARRANTIES</h5>
                            <p>Seller warrants to FCA and its customers that it shall perform all Services hereunder in a competent and professional manner in accordance with the terms of Order, industry accepted standards and all applicable laws and that the Goods shall be free of liens, new and unused, perform in accordance with all applicable specifications, including Seller’s published specifications, and be free from defects in materials, workmanship and design for a period of five (5) years from FCA’s receipt of such Goods. Seller further warrants it has the capability, experience, registrations, licenses, permits, and governmental approvals required to sell the Goods and perform the Services. Seller will perform the Services in a timely, efficient, professional and workmanlike manner in accordance with the applicable Order and to FCA’s satisfaction. Services include all incidental services and tasks necessary to perform the Order and provide acceptable Services. All Services shall be deemed “works made for hire”. To the extent any of the Services are not deemed “works made for hire” by operation of law, Seller hereby irrevocably assigns, transfers and conveys to FCA without further consideration all of its right, title and interest in such Services, including any related or accompanying documentation and any software or other goods necessary for the provisions of the Services, and all rights of patent, copyright, trade secret or other proprietary rights in such materials. Seller acknowledges that FCA shall have the right to obtain and hold in their own name the intellectual property rights in and to such Services and software. Without limiting FCA’s right to pursue any applicable remedies, Goods not meeting this warranty may in particular be returned to Seller for credit or replacement at Seller’s expense, and at FCA’s option, and Services not meeting this warranty shall be re-performed or fees reimbursed, at FCA’s option. Excessive Failure: Should Goods shipped in any ninety (90)-day period to FCA or should all Goods cumulatively received by FCA experience a failure rate of the lesser of any defective-part-per-million specified in the Order or more than zero point three per cent (0.3% = 3000 DPPM’s) from the same defect or more than zero point five percent (0.5% = 5000 DPPM’s) from cumulative defects, Seller shall prepare a plan for diagnosing and addressing the problem and will be responsible for all costs incurred by FCA and its customers in rectifying such failures, including, without limitation, for engineering changes, testing and field-recovery costs, as well as for all damages. All warranties and Service guaranties shall run both to FCA and to its customers.</p>

                            <h5>8. ITEMS FURNISHED BY FCA</h5>
                            <p>Unless otherwise specified by FCA in writing, all designs, tools, patterns, drawings, data, materials, and equipment supplied to Seller or paid for by FCA shall remain the property of FCA, shall be used only for making the Goods or performing the Services for FCA, shall be insured by Seller at replacement value, and shall be returned to FCA in good condition upon completion of Order. Seller assumes all responsibility for the accuracy of tooling used in the production of the Goods or performance of Services, whether such tooling is fabricated by Seller or furnished by FCA.</p>

                            <h5>9. INDEMNITY</h5>
                            <p>Seller agrees to indemnify, defend and hold FCA and its customers harmless from and against any and all claims, actions, losses, expenses, damages, penalties, fines, liabilities and settlements arising from any actual, alleged or threatened third-party claims relating to (a) any infringement, misappropriation or violation on the part of Seller’s Goods or Services of any third party’s patent, copyright, trade secret, mask work, trademark, trademark rights or any other intellectual property right, (b) personal injury or property damage caused by the Goods or Services, (c) defects in the Goods or Services which amount to a breach of Seller’s warranties in Section “Warranties” or “Quality Requirements”; (d) breach of Section “Compliance with Laws”, or (e) as a result of any negligent or reckless act or willful misconduct of the Seller.</p>
                            <p>Should FCA’s use, or use by its distributors, subcontractors or customers, of any Goods or Services purchased from Seller be enjoined, be threatened by injunction, or be the subject of any legal proceeding, Seller shall, at its sole cost and expense, either (a) substitute fully equivalent non-infringing Goods or Services; (b) modify the Goods or Services so that they no longer infringe but remain fully equivalent in functionality; (c) obtain for FCA, its distributors, subcontractors or customers the right to continue using the Goods or Services; or (d) if none of the foregoing is possible, refund all amounts paid for the infringing Goods or Services, plus any and all additional costs incurred by FCA to replace the infringing goods, including but not limited to shipping, installation and any additional cost to purchase substitute goods or services, above the contracted price.</p>

                            <h5>10. CHANGES</h5>
                            <p>FCA may, by Order amendment issued to Seller, change (a) the method of shipment or packing, (b) the drawings, designs, or specifications, (c) the place of delivery, or (d) the shipment date. Seller shall promptly inform FCA of any modifications to the delivery schedule necessitated by the changes. If any Goods are designated non-cancelable/non-returnable (“NCNR”), FCA may reschedule the delivery of any NCNR Goods at any time up to the time of shipment for a period of up to Two Hundred Seventy (270) days beyond the delivery date, and FCA shall not have any liability for any costs associated with such rescheduling. Within three (3) days from receipt of a Order amendment, Seller shall notify FCA in writing of any increase or decrease in the cost of performance caused by a Order amendment and provide supporting documentation. Should Seller modifies the cost of goods prior to shipment, FCA reserves right to cancel the Order regardless of NCNR agreement unless Seller ships the goods at original cost of the executed NCNR. FCA shall make an equitable adjustment in the Order to reflect valid cost variances due to the changes requested by FCA. Seller shall advise FCA in writing of any foreseeable part shortages, and shall advise FCA not less than one (1) year in advance of any changes that might affect Seller’s ability to accept FCA’s Orders.</p>

                            <h5>11. TERMINATION AND REMEDIES</h5>
                            <p>FCA may terminate Order in whole or in part at any time by written notice to Seller, even Orders in which Goods are designated as NCNR. Seller will thereupon immediately (a) stop work on the cancelled Goods or Services; (b) notify its subcontractors to do likewise; (c) cancel orders for components for the cancelled Goods or Services; (d) return unneeded components for cancelled Goods to their suppliers or divert such components to jobs for other customers; and (e) otherwise mitigate all non-returnable, unneeded components for cancelled Goods or Services. Seller shall not be entitled to compensation for cancelled Goods. Except for termination due to default or delay of Seller, Seller shall be entitled to commercially reasonable compensation for NCNR Goods on hand at the termination date as follows:</p>
                            <p>FCA will purchase (a) finished Goods at the Order price, (b) work-in-process Goods at a reasonable pro-rata percentage of the finished Goods Order price and (c) custom components for the cancelled Goods, which Seller properly ordered and was not able to cancel, return, or otherwise mitigate using diligent efforts within ninety (90) days after cancellation, at Seller’s cost for such custom components. The total compensation paid by FCA for such cancellation shall not exceed the price on the Order for the cancelled Goods. In the event that FCA breaches its obligations under Order, and fails to cure within a commercially reasonable time after receiving written notice of such default, Seller’s sole and exclusive remedy shall be to receive direct damages for the Goods in question as if such Goods were cancelled, computed in the manner set forth in the fourth sentence of this section. In no event shall Seller be entitled to indirect, incidental, consequential, special, or punitive damages or loss of profit, for FCA’s breach of the terms and conditions of Order, or for any other act or omission occurring as a result of FCA’s breach of its performance obligations under Order.</p>

                            <h5>12. WAIVER</h5>
                            <p>No claim or right arising out of the breach of Order by Seller can be discharged by a waiver of the claim or right by FCA unless the waiver is supported by consideration and is in writing signed by FCA.</p>

                            <h5>13. ASSIGNMENT</h5>
                            <p>Seller shall not assign its rights or obligations under Order without the advance written consent of FCA. FCA may assign its rights under Order to a subsidiary or affiliate upon written notice to Seller.</p>

                            <h5>14. CONFIDENTIALITY</h5>
                            <p>Seller will acquire knowledge of FCA’s Confidential Information (as defined below) in connection with its performance hereunder and agrees to keep such FCA Confidential Information in confidence during, and following, termination or expiration of this Agreement. “FCA Confidential Information” includes but is not limited to all information, whether written or oral, in any form, including without limitation, information relating to the research, development, products, methods of manufacture, trade secrets, business plans, customers, vendors, finances, personnel data, Work Product (as defined herein) and other material or information considered proprietary by FCA relating to the current or anticipated business or affairs of FCA which is disclosed directly or indirectly to Seller. In addition, FCA Confidential Information means any third party’s proprietary or confidential information disclosed to Seller in the course of providing Services or Goods to FCA. FCA Confidential Information does not include any information (i) which Seller lawfully knew without restriction on disclosure before FCA disclosed it to Seller, (ii) which is now or becomes publicly known through no wrongful act or failure to act of Seller, (iii) which Seller developed independently without use of the FCA Confidential Information, as evidenced by appropriate documentation, or (iv) which is hereafter lawfully furnished to Seller by a third party as a matter of right and without restriction on disclosure. In addition, Seller may disclose Confidential Information that is required to be disclosed pursuant to a requirement of a government agency or law, or otherwise ordered by a court of competent jurisdiction, so long as Seller provides prompt notice to FCA of such requirement prior to disclosure.</p>
                            <p>Seller agrees not to copy, alter or directly or indirectly disclose any FCA Confidential Information. Additionally, Seller agrees to limit its internal distribution of FCA Confidential Information to Seller’s Assistants who have a need to know, and to take steps to ensure that the dissemination is so limited, including the execution by Seller’s Assistants of nondisclosure agreements with provisions substantially similar to those set forth herein. In no event will Seller use less than the degree of care and means that it uses to protect its own information of like kind, but in any event not less than reasonable care to prevent the unauthorized use of FCA Confidential Information.</p>
                            <p>Seller further agrees not to use the FCA Confidential Information except in the course of performing hereunder and will not use such FCA Confidential Information for its own benefit or for the benefit of any third party. The mingling of the FCA Confidential Information with information of Seller shall not affect the confidential nature or ownership of the same as stated hereunder. Seller agrees not to design or manufacture any products which incorporate FCA Confidential Information. All FCA Confidential Information is and shall remain the property of FCA. Upon FCA’s written request or the termination of this Agreement, Seller shall return, transfer or assign to FCA all FCA Confidential Information, including all Work Product, as defined herein, and all copies thereof.</p>

                            <h5>15. QUALITY REQUIREMENTS</h5>
                            <p>Seller shall comply, and shall cause all Goods and Services to comply, with all applicable quality requirements which are incorporated into Order. The following applicable quality requirements are part of our purchase order (when required).</p>

                            <ul>
                                <li><strong>Raw Material</strong> Supplier shall provide report listing following:</li>
                                <ul>
                                    <li>Material specifications</li>
                                    <li>Supplier & Lot number</li>
                                    <li>FCA’s part number, P.O. number and quantity</li>
                                </ul>

                                <li><strong>Test Report </strong> Supplier shall include with shipment, required test, inspection, and verification reports required by the purchase order.</li>
                                <li><strong>Process Certifications (Vendor Performed)</strong> Supplier shall supply reports of all special processes and inspection verification results with each shipment of processed components.</li>
                                <li><strong>Certification of Conformance </strong> Supplier shall provide certificate of conformance documented information with each shipment of product.</li>
                                <li><strong>First Article Inspection</strong> Supplier shall (when required) provide a First Article Inspection Report for product manufactured to purchase order requirements.</li>
                                <li><strong>Source Inspection</strong> Supplier shall (when required) facilitate FCA in-process or final source inspection of product at Supplier facility.</li>
                                <li><strong>Change notification and approval</strong> Supplier shall notify FCA of any changes in product or process definition, supplier location, supplier management changes, etc. In addition, Supplier shall seek approval of changes by FCA.</li>
                                <li><strong>Contract number</strong> The Prime Contract number listed on the FCA purchase order will be recorded on all subcontracts purchase orders. All items shown on this purchase order, including all applicable records, are subject to surveillance and inspection at your facility, at the option of Government, regulatory agencies, and/or FCA’s customer representative. FCA will provide sufficient notice to schedule surveillance.</li>
                                <li><strong>Inspection system</strong> Supplier shall maintain an inspection system in compliance with ISO 9001, AS9100, or equivalent. Documented information retained by Suppliers shall be retained for 7 years minimum. (For disposition records, contact FCA’s Quality Department.)</li>
                                <li><strong>Calibration system</strong> Supplier shall provide and maintain a calibration system in compliance with MIL-STD-45662 or AS9100 7.1.5 requirement, or equivalent.</li>
                                <li><strong>Notification of nonconformance</strong> Supplier shall notify FCA of nonconforming processes, products, or services and when required, the supplier shall obtain the organizations approval for disposition.</li>
                                <li><strong>Special process control </strong> Supplier shall notify FCA of changes to processes, products, or services including changes of their external providers or location of manufacture and will obtain the organizations approval.</li>
                                <li><strong>FCA process control </strong> Supplier shall use customer-designated or approved external providers, including process sources (e.g., special processes)</li>
                                <li><strong>Customer/Government source</strong> FCA customer and/or Government source inspection/verification requirements may be required at your facility. Customer or Government Agency may still reject subsequent delivered product.</li>
                                <li><strong>Key characteristics</strong>Supplier shall recognize any special requirements, critical items, or key characteristics identified by FCA. Where these requirements are specified, Supplier shall not alter. Requirements as stated, shall require a 100%-dimensional inspection record.</li>
                                <li><strong>Right of Access by the Purchaser</strong>Supplier shall provide and agree to right of access by the organization, their customer, and any regulatory authorities to the applicable areas of facilities and to applicable documented information at any level of the supply chain.</li>
                                <li><strong>FOD</strong>Supplier shall ensure that Foreign Object Debris/Damage (FOD) is prevented and/or removed before shipment. In addition, this requirement shall be flowed down to sub tier Suppliers.</li>
                                <li><strong>AS9100 requirements For Counterfeit Prevention Control Program</strong>Supplier shall comply with the requirements of AS9100 8.1.4 Prevention of Counterfeit Parts or equivalent, and AS9100 8.4.3 Information for External Providers.</li>
                                <li><strong>AS9100 requirements under 8.4.3</strong></li>
                                <ul>
                                    <li>The Supplier shall use customer designated or approved external providers and process sources.</li>
                                    <li>The Supplier will flow down to sub-tier suppliers, these terms and conditions &amp; requirements.</li>
                                    <li>The Supplier shall ensure that employees are aware of their contribution to product service or conformity; their contribution to product safety; and the importance of ethical behavior when accomplishing their job responsibilities.</li>
                                </ul>
                                <li><strong>Human Trafficking</strong>As an organization, FCA strives to give visibility and a voice to those who are caught in Human Trafficking. The facts regarding this epidemic serve as a reminder to our organization to use companies of a like-minded conviction so as to reduce and eventually stop the Human Trafficking trade.</li>
                                <li><strong>Country of origin / Certificate of origin (COO)</strong>Supplier shall indicate on the quote, order, or packing slip with shipment the country of origin / certificate of origin (COO).</li>
                                <li><strong>Supplier Performance</strong>Supplier ratings are: 1) Exceptional (97.00 to 100%), 2) Acceptable (95.00 to 96.99%), 3) Marginal (91.00 to 94.99%), and 4) Not Acceptable (Below 91.00%). Supplier shall maintain performance to stay as an approved supplier. Quantity and Quality issues will be communicated to supplier in writing to improve performance as required. Supplier failing to improve performance above acceptable level will lose opportunity to do business with FCA.</li>
                            </ul>

                            <h5>16. COMPLIANCE WITH LAWS</h5>
                            <ul>
                                <li>General: Seller shall comply fully with all applicable federal, state and local laws in the performance of this Agreement including, but not limited to, all applicable employment laws, tax laws or regulations, export controls and environmental laws and regulations.</li>
                                <li>Equal Employment Opportunity: At times, FCA may be a government contractor and is subject to the requirements of Executive Order 11246, the Rehabilitation Assistance Act. Pursuant to these requirements, the Equal Opportunity Clauses found at 41 Code of Federal Regulations sections 60-1.4(a) (1-7), 60-250.4(a-m) and 60-741.5 (a) (1-6) are incorporated herein by reference as though set forth at length, and made an express part of this Agreement. If applicable, Seller will comply with the following Federal Acquisition Regulations: (i) 52.222-26 “Equal Opportunity”, (ii) 52.222-35 “Affirmative Action for Special Disabled and Vietnam Veterans”, (iii) 52.222-36 “Affirmative Action for Handicapped Workers.”</li>
                                <li>Small Business Plan Requirements: At times, FCA may be a government contractor and is subject to the requirements of FAR section 52.219. Pursuant to FAR 52.219.9, if Seller (i) is not considered a Small Business (as the term is defined in section 3 of the Small Business Act) and (ii) is providing Goods or Services under this Agreement in an amount greater than or equal to $500,000, and (iii) is subcontracting a portion of the Goods or Services from a third party, Seller agrees to submit to FCA a Small Business Plan or letter stating that Seller does not have a Small Business Plan and listing the approximate dollar amount to be subcontracted.</li>
                                <li>Hazardous Materials: If Goods include hazardous materials, Seller represents and warrants that Seller understands the nature of any hazards associated with the manufacture, handling and transportation of such hazardous materials and assumes all responsibility for the safe and proper handling of, utilization of, storage of and disposal of such materials.</li>
                                <li>Customs: Upon FCA’s request, Seller will promptly provide FCA with a statement of origin for all Goods and United States Customs documentation for Goods wholly or partially manufactured outside of the United States.</li>
                            </ul>

                            <h5>17. OWNERSHIP OF WORK PRODUCT</h5>
                            <p>For purposes of this Agreement, “Work Product” shall include, without limitation, all designs, discoveries, creations, works, devices, masks, models, work in progress, Service deliverables, inventions, products, computer programs, procedures, improvements, developments, drawings, notes, documents, business processes, information and materials made, conceived or developed by Seller alone or with others which result from or relate to the Services performed hereunder. Standard Goods manufactured by Seller and sold to FCA without having been designed, customized or modified for FCA do not constitute Work Product. All Work Product shall at all times be and remain the sole and exclusive property of FCA. Seller hereby agrees to irrevocably assign and transfer to FCA and does hereby assign and transfer to FCA all of its worldwide right, title and interest in and to the Work Product including all associated intellectual property rights. FCA will have the sole right to determine the treatment of any Work Product, including the right to keep it as trade secret, execute and file patent applications on it, to use and disclose it without prior patent application, to file registrations for copyright or trademark in its own name or to follow any other procedure that FCA deems appropriate. Seller agrees: (a) to disclose promptly in writing to FCA all Work Product in its possession; (b) to assist FCA in every reasonable way, at FCA’ expense, to secure, perfect, register, apply for, maintain, and defend for FCA’ benefit all copyrights, patent rights, mask work rights, trade secret rights, and all other proprietary rights or statutory protections in and to the Work Product in FCA’ name as it deems appropriate; and (c) to otherwise treat all Work Product as FCA Confidential Information as described above. These obligations to disclose, assist, execute and keep confidential survive the expiration or termination of this Agreement. All tools and equipment supplied by FCA to Seller shall remain the sole property of FCA.</p>
                            <p>Seller will ensure that Seller’s Assistants appropriately waive any and all claims and assign to FCA any and all rights or any interests in any Work Product or original works created in connection with this Agreement. Seller irrevocably agrees not to assert against FCA or its direct or indirect customers, assignees or licensees any claim of any intellectual property rights of Seller affecting the Work Product.</p>
                            <p>FCA will not have rights to any works conceived or reduced to practice by Seller which were developed entirely on Seller’s own time without using equipment, supplies, facilities or trade secret or FCA Confidential Information, unless (i) such works relate to FCA’ business, or FCA’ actual or demonstrably anticipated research or development, or (ii) such works result from any Services performed by Seller for FCA.</p>

                            <h5>18. NONINTERFERENCE WITH BUSINESS</h5>
                            <p>Seller agrees not to unlawfully interfere with the business of FCA in any manner, and, during, and for a period of two years immediately after the termination or expiration of this Agreement, Seller further agrees not to solicit or induce any employee or independent contractor to terminate or breach an employment, contractual or other relationship with FCA.</p>

                            <h5>19. TERMINATION</h5>
                            <p>FCA may terminate this Agreement upon written notice to Seller if Seller fails to perform or otherwise breaches this Agreement, files a petition in bankruptcy, becomes insolvent, or dissolves. In the event of such termination, FCA shall pay Seller for the portion of the Services satisfactorily performed and those conforming Goods delivered to FCA through the date of termination, less appropriate offsets, including any additional costs to be incurred by FCA in completing the Services.</p>
                            <p>FCA may terminate this Agreement, or any Service(s), for any other reason upon thirty (30) days’ written notice to Seller. Seller shall cease to perform Services and/or provide Goods under this Agreement on the date of termination specified in such notice. In the event of such termination, FCA shall be liable to Seller only for those Services satisfactorily performed and those conforming Goods delivered to FCA through the date of termination, less appropriate offsets.</p>
                            <p>Seller may terminate this Agreement upon written notice to FCA if FCA fails to pay Seller within sixty (60) days after Seller notifies FCA in writing that payment is past due.</p>
                            <p>Upon the expiration or termination of this Agreement for any reason: (a) each party will be released from all obligations to the other arising after the date of expiration or termination, except for those which by their terms survive such termination or expiration; and (b) Seller will promptly notify FCA of all FCA Confidential Information or any Work Product in Seller’s possession and, at the expense of Seller and in accordance with FCA’s instructions, will promptly deliver to FCA all such FCA Confidential Information and/or Work Product.</p>

                            <h5>20. REMEDIES</h5>
                            <p>If Seller breaches this Agreement, FCA shall have all remedies available by law and at equity. For the purchase of Goods, Seller’s sole remedy in the event of breach of this Agreement by FCA shall be the right to recover damages in the amount equal to the difference between market price at the time of breach and the purchase price specified in the Agreement. No alternate method of measuring damages shall apply to this transaction. Seller shall have no right to resell Goods for FCA’ account in the event of wrongful rejection, revocation of acceptance, failure to make payment or repudiation by FCA and any resale so made shall be for the account of Seller. In the event Seller breaches this Agreement, Seller shall pay any and all costs and reasonable attorneys’ fees incurred in enforcing any aspect of this Agreement.</p>

                            <h5>21. FORCE MAJEURE</h5>
                            <p>FCA shall not be liable for any failure to perform including failure to (i) accept performance of Services or, (ii) take delivery of the Goods as provided caused by circumstances beyond its control which make such performance commercially impractical including, but not limited to, acts of God, fire, flood, acts of war, government action, accident, labor difficulties or shortage, inability to obtain materials, equipment or transportation. In the event FCA is so excused, either party may terminate the Agreement and FCA shall at its expense and risk, return any Goods received to the place of shipment.</p>

                            <h5>22. SEVERABILITY</h5>
                            <p>If any provision of this Agreement shall be deemed to be invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby.</p>

                            <h5>23. LIMITATION OF LIABILITY</h5>
                            <p>IN NO EVENT SHALL FCA BE LIABLE TO SELLER OR SELLER’S ASSISTANTS, OR ANY THIRD PARTY FOR ANY INCIDENTAL, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF, OR IN CONNECTION WITH, THIS AGREEMENT, WHETHER OR NOT FCA WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>

                            <h5>24. ASSIGNMENT; WAIVER</h5>
                            <p>Seller may not assign this Agreement or any of its rights or obligations under this Agreement, without the prior written consent of FCA. Any assignment or transfer without such written consent shall be null and void. This Agreement shall inure to the benefit of, and be binding upon, the successors and assigns of FCA without restriction. Any waiver of any default hereunder or of any term or condition of this Agreement shall not be deemed to be a continuing waiver or a waiver of any other default or any other term or condition.</p>

                            <h5>25. NONEXCLUSIVE AGREEMENT</h5>
                            <p>This is not an exclusive agreement. FCA is free to engage others to perform Services or provide Goods the same as or similar to Seller’s. Seller is free to, and is encouraged to, advertise, offer and provide Seller’s Services and/or Goods to others; provided however, that Seller does not breach this Agreement.</p>

                            <h5>NOTICES</h5>
                            <p>Except for Purchase Orders which may be sent by local mail, facsimile transmission, or electronically transmitted, all notices, and other communications hereunder shall be in writing, and shall be addressed to Seller or to an authorized FCA representative, and shall be considered given when (a) delivered personally, (b) sent by confirmed telex or facsimile, (c) sent by commercial overnight courier with written verification receipt, or (d) three (3) days after having been sent, postage prepaid, by first class or certified mail.</p>

                            <h5>27. SURVIVAL OF OBLIGATIONS</h5>
                            <p>Any obligations and duties that, by their nature, extend beyond the expiration or termination of this Agreement shall survive the expiration or termination of this Agreement.</p>

                            <h5>28. GOVERNING LAW</h5>
                            <p>This Agreement shall be construed in accordance with, and disputes shall be governed by, the laws of the State of Illinois, excluding its conflict of law rules. The Circuit Court of the County of Cook or the United States District Court for the Northern District of Illinois shall have jurisdiction and venue over all controversies arising out of, or relating to, this Agreement. The applicability of the UN Convention on Contracts for the International Sale of Goods is hereby expressly waived by the parties and it shall not apply to the terms and conditions of this Agreement.</p>

                            <h5>29. ENTIRE AGREEMENT; MODIFICATION</h5>
                            <p>This Agreement, together with any specifications provided to Seller, is the complete, final and exclusive statement of the terms of the agreement between the parties and supersedes any and all other prior and contemporaneous negotiations and agreements, whether oral or written, between them relating to the subject matter hereof. This Agreement may not be varied, modified, altered, or amended except in writing, including a purchase order or a change order issued by FCA, signed by the parties. The terms and conditions of this Agreement shall prevail notwithstanding any variance with the terms and conditions of any acknowledgment or other document submitted by Seller. Notwithstanding the foregoing, this Agreement will not supersede or take the place of any written agreement which is signed by both parties and covers the same subject matter as this Agreement or its related purchase orders.</p>

                            <h5>30. INJUNCTIVE RELIEF</h5>
                            <p>Seller acknowledges and agrees that the obligations and promises of Seller under this Agreement are of a unique, intellectual nature giving them particular value. Seller’s breach of any of the promises contained in this Agreement will result in irreparable and continuing damage to FCA for which there will be no adequate remedy at law and, in the event of such breach, FCA will be entitled to seek injunctive relief, or a decree of specific performance.</p>

                            <h5>31. ELECTRONIC COMMUNICATIONS</h5>
                            <p>FCA Purchase Orders may be faxed, emailed and/or directly sent from the companies ERP/MRP system. These documents display a signature line, typically blank when documents are traded electronically. These purchase Orders are to be considered as legally signed, binding offers to purchase according to the details as shown on each purchase order and subject to the terms and conditions included above.</p>


                            <h2>Terms & Conditions for Customers</h2>
                            <h3>Terms & Conditions for S & M Group, Inc. dba Flextron Circuit Assembly(FCA)'s Customers, applicable to the Customer's Purchase Orders (FCA's Sales Orders)</h3>
                            <h4>All Customer’s Purchase Orders are subject to S & M Group, Inc. dba Flextron Circuit Assembly (Seller)’s terms and conditions as below including special and additional requirement parts</h4>

                            <ul>
                                <li><strong>SHIPPING AND PACKAGING :</strong> Shipping Origin Location is F.O.B. Flextron Circuit Assembly(FCA), Wood Dale, IL 60191 USA. A Packaging Charge will be billed for all orders which require specialty or individual packaging. All applicable shipping charges will the responsibility of the customer on all shipments. Any agreed disputed shipping charges billed will be reimbursed in form of Credit to Customer Account by FCA.</li>

                                <li>
                                    <strong>1. Governing Terms:</strong> By accepting this FCA’s shipment Buyer agrees to these terms and conditions of sale and agrees they shall supersede those of Buyer, if any, annually instances where conflict exists. Any additional,
                                    consistent or different terms and conditions contained in Buyer’s Purchases Order or other documents submitted by Buyer to Seller at any time, whether before or after the date hereof, are hereby expressly rejected by Seller. Buyer
                                    acknowledges that, notwithstanding anything to the contrary contained in its Purchase Order or other documents, receipt and acceptance by Buyer of Seller’s goods shall constitute acceptance by Buyer of these terms and conditions.
                                </li>
                                <li>
                                    <strong>2. Prices:</strong> All prices quoted by Seller are subject to change at any time and to any addition which may be necessary to cover any tax or charge now existing or hereafter imposed by Federal, State or Municipal Authorities
                                    upon equipment, materials or services sold by Seller for the production, sale, distribution or delivery thereof, or upon any feature of this transaction. Seller reserves the right to correct all typographical or clerical errors which
                                    may be present in Seller’s prices or specifications.
                                </li>
                                <li>
                                    <strong>3. Acceptance of Orders:</strong> An Order shall be binding on Buyer. All orders placed by Buyer with Seller are accepted conditional upon Buyer’s assent of these terms and conditions. If Buyer does not accept the goods on these
                                    terms and conditions, the goods are to be returned at once to Seller as shipped. No agreement or understanding, oral or written, in any way purporting to these terms or conditions, whether contained in Buyer’s purchase or shipping
                                    release forms, or elsewhere, will be binding upon Seller unless hereafter made in writing and signed by its authorized representative. All proposals, negotiations and representations made prior, and with reference, hereto are merged
                                    herein. Orders transmitted via email shall be deemed non-binding unless the email is successfully delivered to FCA and acknowledged in writing by FCA as accepted. It is the responsibility of the Buyer to obtain a formal Order Acceptance
                                    Acknowledgement from FCA to confirm the validity of the order. FCA assumes no liability for undelivered or unacknowledged orders.
                                </li>
                                <li>
                                    <strong>4. Payment and Credit:</strong> Each shipment shall be a separate transaction and payment shall be made accordingly. Unless otherwise specified, payment shall be made on the basis of net cash, credit terms from the date of
                                    invoice. No cash discounts are allowed unless otherwise specifically provided by Seller. If, in the exclusive judgment of Seller, the financial condition of Buyer at any time does not justify the commencement or continuance of
                                    production or shipment on the terms specified herein, Seller may, in addition to all other remedies it may have at law or in equity, make a written demand for full or partial payment in advance, suspend its per- dormancy until such
                                    payment is made and cancel the Buyer’s order if such payment is not received by Seller within 30 days after delivery in person or mailing of such demand by Seller. If Buyer fails to pay within 10 days after the due date thereof any sum
                                    required to be paid by Buyer to Seller hereunder, Buyer will pay to Seller for each delinquent payment or part thereof interest on such delinquent amount from the due date thereof until at the rate of 18% per annum, provided that if
                                    applicable law imposes a lesser late charge for contracts of this type involving Buyer, the above late charge will be reduced to the limit allowed by, and be paid in accordance with, such applicable law. Buyer shall also pay to Seller
                                    all reasonable costs and expenses (including but not limited to Attorneys fees) incurred by Seller in connection with Seller’s efforts to collect such delinquent payment or payments.
                                </li>
                                <li>
                                    <strong>5. Security Interest:</strong> Seller shall have and Buyer does hereby grant a purchase money security interest in all the goods sold hereunder, together with all proceeds and replacements until all charges have been paid in
                                    full. Seller may file or record this or any other applicable document necessary to protect the interests of Seller in the goods. Buyer shall execute and deliver any document reasonably requested by Seller for such purpose.
                                </li>
                                <li>
                                    <strong>6. Shipment:</strong> Shipment is FOB shipping point unless specifically provided by Seller. The shipping date is estimated upon the basis of immediate receipt by Seller of all information required to be furnished by Buyer.
                                    Seller shall, in good faith, endeavor to ship the estimated shipping date, but reserves the right to vary such date free of any liability to Buyer, Buyer may explicitly state the method of shipment preferred. In the absence of shipping
                                    information, Seller will use its discretion in employing the method of shipment for the goods ordered. Due to the custom manufacturing nature of the products, FCA reserves the right to ship quantities up to 3% over or under the ordered
                                    quantity. Any such over or under shipment will be deemed acceptable and will be invoiced accordingly. The Buyer acknowledges and agrees to this allowance and accepts that no additional liability shall arise for FCA in relation to such
                                    quantity variances.
                                </li>
                                <li><strong>7. Deliveries:</strong> Seller will not assume any responsibility for any damage resulting from any delays beyond its control.</li>
                                <li><strong>8. Returns:</strong> No goods may be returned to Seller without the prior written consent of Seller and are subject to a return charge.</li>
                                <li>
                                    <strong>9. Cancellation by Seller:</strong> Seller may, by written notice to Buyer and without any liability, cancel Buyer’s order if Buyer (i) fails to perform any of the terms and conditions hereof and does not cure such failure
                                    within a period of 10 days after receipt of written notice from Seller specifying such failure; (ii) in Seller’s opinion has not established or maintained credit to meet promptly the payment terms imposed by Seller in Section 4 herein;
                                    (iii) becomes insolvent, makes an assignment in favor of creditors, or becomes subject to any bankruptcy, dissolution, or similar proceedings; or (iv) is merged into, or all or a substantial part of its assets are sold to, another
                                    company. As a nonexclusive alternative to cancellation, Seller may, by written notice to Buyer and without any liability, suspend any of its obligation hereunder for any reason referenced in subsections (i)-(iv) of this Section 9.
                                </li>
                                <li>
                                    <strong>10. Cancellation by Buyer:</strong> Buyer may, by prior written notice to Seller, cancel orders or defer deliveries only on the conditions that Buyer assumes immediate liability and makes payments to Seller for cancellation
                                    charges incurred on the basis of costs to Seller, including handling and overhead charges. All cancellation charges will be determined at the time of cancellation or deferment.
                                </li>
                                <li>
                                    <strong>11. Taxes:</strong> Any sales tax applicable to the sale and any tax, impost, levy, duty or other charge hereafter imposed by any government or other authority upon the production, use or sale of any goods or upon the materials,
                                    methods or machines for producing the same and any increase in cost to Seller in manufacturing, processing or delivering any goods resulting directly from government supervision, regulation, or control, now or hereafter prescribed by
                                    law or in force, and affecting Seller’s performance of its obligations, will be added to the purchase price as herein noted or any revisions thereof, will be paid by Buyer.
                                </li>
                                <li>
                                    <strong>12. NCNR &amp; ReSchedules:</strong> Every custom manufactured product &amp; all Commercially Off-The-Shelf (COTS) part listed on the Buyer’s Purchase Order is subject to the NCNR. Buyer’s Purchase Order requires custom
                                    fabrications, components or materials specific to Buyer’s product only, Buyer acknowledges and agrees to non-cancelable / non-returnable (NCNR) nature of the products. The entire Purchase Order &amp; all agreed subsequent Purchase Order
                                    changes shall be considered as non-cancelable, non-returnable. The Purchase Order cannot be rescheduled for a shipment date later than the original requested/scheduled ship date unless agreed by Seller. Seller will make every effort to
                                    meet Buyer’s requested ship date, but cannot commit to a firm ship date until materials/components have been received from Seller’s suppliers and the order has been placed into Seller’s production schedule. Any delays by Seller,
                                    including any/all force majeure events, in delivering the purchased items shall not affect the binding character of NCNR. Should the Buyer not take delivery of the product by the specified delivery date, the Buyer agrees to inventory
                                    carrying charges at the Prime Interest Rate of the remaining balance of the Purchase Order.
                                </li>
                                <li>
                                    <strong>13. Limit of Seller’s Liability Buyer’s Remedy:</strong> IN NO EVENT SHALL SELLER BE LIABLE FOR SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, WHETHER IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, INCLUDING
                                    WITHOUT LIMITATION DAMAGES FOR INJURY TO PERSON OR PROPERTY, LOST PROFITS OR REVENUE, LOST SALES OR LOSS OF USE OF ANY PRODUCT. BUYER’S SOLE AND EXCLUSIVE REMEDY AGAINST SELLER SHALL BE THE REPLACEMENT OF NONCONFORMING GOODS AS PROVIDED
                                    HEREIN. SELLER’S LIABILITY ON ANY CLAIM, WHETHER IN CONTRACT, TORT, REFLUENCE, STRICT LIABILITY OR OTHERWISE, OR ANY LOSS OR DAMAGE ARISING OUT OF OR IN CONNECTION WITH BUYER’S ORDER, SHALL IN NO CASE EXCEED THE PURCHASE PRICE OF THE
                                    ORDER. THE SOLE PURPOSE OF THE STIPULATION OF THE EXCLUSIVE REMEDY PROVIDED FOR HEREIN SHALL BE TO PROVIDE BUYER WITH REPLACEMENT OF NONCONFORMING GOODS IN THE MANNER PROVIDED HEREIN. SUCH REMEDY SHALL NOT BE DEEMED TO HAVE FAILED OF
                                    ITS ESSENTIAL PURPOSE SO LONG AS SELLER IS WILLING AND ABLE TO REPLACE NONCONFORMING GOODS IN THE PRESCRIBED MANNER.
                                </li>
                                <li>
                                    <strong>14. Force Majeure:</strong> Delays by the Seller or by the Buyer in the performance of this contract shall be excused whenever the Seller or the supplying manufacturer is prevented from producing or delivering, or the Buyer from
                                    receiving or using the above material, by strikes, differences with workmen, fires, accidents, delays or difficulties in transportation, acts of God or the public enemy, or other causes beyond the reasonable control of the Buyer or of
                                    the Seller or of the supplying manufacturer, as well as acts or demands of the government in times of war or national emergency. Any such delayed performance, however, shall not in any way invalidate this contract or any part thereof.
                                </li>
                                <li>
                                    <strong>15. Indemnification:</strong> The Buyer will indemnify the Seller against and hold harmless from any and all claims, actions, proceedings, expenses, damages, liabilities, penalties, liens, costs and expenses, including
                                    attorney’s fees (including any of the foregoing arising or imposed without Seller’s fault or negligence or under the doctrine of strict liability) arising in connection with the goods. Buyer agrees that upon written notice by Seller of
                                    the assertion of any of the foregoing against Seller, Buyer will assume full responsibility for the defense thereof. All claims by Buyer against Seller must be made in writing to Seller within 10 days after the receipt of the goods and
                                    prior utilization of the goods by Buyer. Failure to give such notice within such time will constitute a waiver by Buyer of all claims wish respect to such goods.
                                </li>
                                <li>
                                    <strong>16. Warranty:</strong> FCA WARRANTS ONLY THAT SUBJECT TO VARIATIONS PERMISSIBLE IN THE INDUSTRY THE GOODS WILL CONFORM TO SPECIFICATIONS PROVIDED BY THE FCA AND AGREED TO BY THE BUYER. IN THE EVENT THE GOODS FAIL TO CONFORM TO
                                    SUCH SPECIFICATIONS &amp; APPROVED DEVIATIONS, FCA SHALL REPAIR OR REPLACE THE NONCONFORMING GOODS. FCA MAKES NO OTHER WARRANTIES, REPRESENTATIONS OR COVENANTS, EXPRESS OR IMPLIED, WITH RESPECT TO THE GOODS AS TO ANY MATTER WHATSOEVER,
                                    INCLUDING BUT NOT LIMITED TO WARRANTIES, REPRESENTATIONS OR COVENANTS AS TO THE WORKMANSHIP, QUALITY, CONDITION, OR MERCHANTABLE OR FITNESS FOR ANY PARTICULAR PURPOSE OF GOODS. FCA warrants (i) that it will manufacture the Product in
                                    accordance with IPC Workmanship Standards (ii) that at the time of manufacture, the Product will conform, in all material respects, to the Specifications assigned by CUSTOMER. The above warranty shall remain in effect for a period of
                                    twelve (12) months from the date any Product is initially delivered to CUSTOMER (“Warranty Period”). (a) Repair or Replacement of Defective Product: In accordance with FCA’s standard return material authorization process and procedure
                                    (“RMA”), FCA will either repair or replace, any Product that contains a defect caused by a breach of the warranty set forth in this Section (a) above provided that the Product is received within forty five (45) days following the end of
                                    any applicable Warranty Period (“RMA Product”). If CUSTOMER desires to return a Product based on a claim of breach of the warranty set forth in this Section, CUSTOMER shall request an RMA number from FCA. CUSTOMER shall then consign the
                                    alleged defective Product, FOB FCA’s designated repair facility, and specify the FCA assigned RMA number. FCA will analyze any such RMA Product and, if a breach of warranty is found (“Defect”), then FCA will repair or replace the RMA
                                    Product within sixty (60) business days of receipt by FCA of the RMA Product and all required associated documentation. In the event a Defect is found, FCA will reimburse CUSTOMER for the reasonable cost of transporting the RMA Product
                                    to FCA’s designated repair facility and FCA will deliver the repaired RMA Product or its replacement, FOB CUSTOMER’s designated destination. If no such Defect is found, CUSTOMER is to reimburse FCA for the cost to repair or replace the
                                    non-Defective RMA Product and CUSTOMER shall bear responsibility for all transportation costs to and from FCA’s designated repair facility. Any warranty for components and printed circuit boards procured by FCA will be limited to the
                                    warranties expressed by the component or printed circuit board manufacturer. The total extent of financial liability to FCA will be no greater than the total value of the labor and material at FCA’s cost for the specific assembly. This
                                    comprises the complete warranty by FCA. No other warranties are expressed or implied. In no event will FCA be held liable for any direct, indirect, consequential or incidental damages resulting from any defect or other related items and
                                    processes, including, but not limited to, any interruption of service, loss of business, anticipated profit, or other consequential damages. (b) Brokered parts/Components Brokered parts are purchased outside normal lines of Distribution
                                    with Customer’s knowledge and approval to purchase. Brokered parts carry NO WARRANTY from FCA and any related replacement, repair and/or rework to such parts are the sole responsibility of CUSTOMER. (c) Parts/Components purchased from
                                    Customer Mandated Suppliers/Manufacturers (where tooled at or sourced at due to any business reason) carry NO WARRANTY from FCA and any related replacement, repair and/or rework to such parts are the sole responsibility of CUSTOMER. (d)
                                    Limitation of Warranty THE REMEDY SET FORTH IN SECTION (b) SHALL CONSTITUTE CUSTOMER’S SOLE AND EXCLUSIVE REMEDY FOR A BREACH OF THE WARRANTY MADE BY FCA HEREIN OR ANY OTHER OBLIGATION OF FCA HEREUNDER. THE WARRANTY SET FORTH IN THIS
                                    SECTION IS IN LIEU OF, AND FCA EXPRESSLY DISCLAIMS, AND CUSTOMER EXPRESSLY WAIVES, ALL OTHER WARRANTIES AND REPRESENTATIONS OF ANY KIND WHATSOEVER WHETHER EXPRESS, IMPLIED, STATUTORY, ARISING BY COURSE OF DEALING OR PERFORMANCE, CUSTOM,
                                    USAGE IN THE TRADE OR OTHERWISE, INCLUDING ANY WARRANTY OF MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE OR INFRINGEMENT OR MISAPPROPRIATION OF ANY RIGHT, TITLE OR INTEREST OF CUSTOMER OR ANY THIRD PARTY. CUSTOMER UNDERSTANDS AND
                                    AGREES THAT IT SHALL HAVE FULL AND EXCLUSIVE LIABILITY WITH RESPECT TO ANY PRODUCT, WHETHER FOR PRODUCT DESIGN LIABILITY, PRODUCT LIABILITY, DAMAGE TO PERSON OR PROPERTY AND/OR INFRINGEMENT OR MISAPPROPRIATION OF THIRD PARTY RIGHTS. NO
                                    ORAL OR WRITTEN STATEMENT OR REPRESENTATION BY FCA, ITS AGENTS OR EMPLOYEES SHALL CONSTITUTE OR CREATE A WARRANTY OR EXPAND THE SCOPE OF ANY WARRANTY HEREUNDER. FCA’S WARRANTY SHALL NOT APPLY TO ANY PRODUCT FCA DETERMINES TO HAVE BEEN
                                    SUBJECTED TO TESTING FOR OTHER THAN SPECIFIED ELECTRICAL CHARACTERISTICS OR TO OPERATING AND/OR ENVIRONMENTAL CONDITIONS IN EXCESS OF THE MAXIMUM VALUES ESTABLISHED IN APPLICABLE SPECIFICATIONS, OR TO HAVE BEEN THE SUBJECT OF
                                    MISHANDLING, ACCIDENT, MISUSE, NEGLECT, IMPROPER TESTING, IMPROPER OR UNAUTHORIZED REPAIR, ALTERATION, DAMAGE, ASSEMBLY, PROCESSING OR ANY OTHER INAPPROPRIATE OR UNAUTHORIZED ACTION OR INACTION THAT ALTERS PHYSICAL OR ELECTRICAL
                                    PROPERTIES. THIS WARRANTY SHALL NOT APPLY TO ANY DEFECT IN THE PRODUCT ARISING FROM ANY DRAWING, DESIGN, SPECIFICATION, PROCESS, TESTING, OR OTHER PROCEDURE, ADJUSTMENT OR MODIFICATION SUPPLIED AND/OR APPROVED BY CUSTOMER.
                                </li>
                                <li>
                                    <strong>17. Nonnative:</strong> No covenant or condition herein can be waived except by the written consent of Seller. Forbearance, waiver or indulgence by Seller in any regard whatsoever will not constitute a waiver of the covenant or
                                    condition to be performed by Buyer to which the same may apply. Waiver by Seller of any breach of these provisions shall not be construed as a waiver of any future breach. Until complete performance by Buyer of said covenant or
                                    condition, Seller shall be entitled to invoke any remedy available to Seller as provided herein or by law in equity despite said forbearance or indulgence.
                                </li>
                                <li>
                                    <strong>18. Serviceability:</strong> No provision of these terms and conditions which may be deemed invalid or enforceable against the parties or their successors or assigns, will in any way invalidate or make enforceable any other
                                    provisions of these terms and conditions, all of which will remain in full force and effect.
                                </li>
                                <li>
                                    <strong>19. Assignment:</strong> These terms and conditions shall not be assigned, subcontracted or delegated, in whole or in part, without Seller’s prior written consent. The provisions of these terms and conditions shall be binding
                                    upon and inure to the benefit of the parties and their successors and assigns.
                                </li>
                                <li>
                                    <strong>20. Governing Law:</strong> The terms and conditions shall be governed by and interpreted in accordance with the law of the State of Illinois. Any legal action or proceeding arising from or in connection with these terms and
                                    conditions shall be brought exclusively in the Courts of the State of Illinois. Buyer hereby irrevocably consents to service of process out of said State of Illinois or U.S. Courts in any action or proceeding by mailing copies thereof
                                    by U.S. mail to Buyer or any other method of service permitted by such Courts.
                                </li>

                            </ul>

                        </div>
                    </div>
                </section>
            </main>
        </>
    )
}

export default TermsConditionsPage